matrix:
  include:
    - language: csharp
      mono: none
      sudo: required
      dist: xenial
      dotnet: 2.2
      before_script:
      - chmod a+x ./build.sh
      script:
      - ./build.sh

    - language: node_js
      node_js:
        - "stable"
      cache:
        directories:
        - "node_modules"
      before_script:
        - chmod a+x ./build-client.sh
      script: 
        - ./build-client.sh